services:
  - type: web
    name: inventory-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_SKJP7uqa6tlb@ep-shiny-fire-a997p03r-pooler.gwc.azure.neon.tech/neondb?sslmode=require
      - key: SQLALCHEMY_DATABASE_URI
        sync: false
        value: postgresql://neondb_owner:npg_SKJP7uqa6tlb@ep-shiny-fire-a997p03r-pooler.gwc.azure.neon.tech/neondb?sslmode=require
      - key: SECRET_KEY
        generateValue: true
    autoDeploy: true 