"""Add performance optimization indexes

Revision ID: f0aebcfbb82a
Revises: 3b8dc143e9ba
Create Date: 2025-03-08 12:10:44.617268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0aebcfbb82a'
down_revision = '3b8dc143e9ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index('idx_customer_name', ['name'], unique=False)
        batch_op.create_index('idx_customer_phone', ['phone'], unique=False)

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.create_index('idx_invoice_customer_id', ['customer_id'], unique=False)
        batch_op.create_index('idx_invoice_date', ['date'], unique=False)
        batch_op.create_index('idx_invoice_payment_status', ['payment_status'], unique=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index('idx_product_description', ['description'], unique=False)
        batch_op.create_index('idx_product_item_code', ['item_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index('idx_product_item_code')
        batch_op.drop_index('idx_product_description')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_index('idx_invoice_payment_status')
        batch_op.drop_index('idx_invoice_date')
        batch_op.drop_index('idx_invoice_customer_id')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index('idx_customer_phone')
        batch_op.drop_index('idx_customer_name')

    # ### end Alembic commands ###
